-- if true then
--   return {}
-- end
return {
  -- add any tools you want to have installed below
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "ansible-language-server",
        "ansible-lint",
        "bash-language-server",
        "beautysh",
        "copilot-language-server",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "golangci-lint-langserver",
        "helm-ls",
        "html-lsp",
        "htmlbeautifier",
        "lua-language-server",
        "markdownlint",
        "npm-groovy-lint",
        "opa",
        "prettier",
        "prettierd",
        "pyright",
        "regal",
        "regols",
        "shellcheck",
        "shfmt",
        "snyk",
        "sonarlint-language-server",
        "stylua",
        "templ",
        "termux-language-server",
        "terraform-ls",
        "trivy",
        "typescript-language-server",
        "usort",
        "vtsls",
        "yaml-language-server",
        "yamlfix",
        "yamlfmt",
        "yamllint",
        "yq",
      },
    },
  },
}
