return {

  -- add any tools you want to have installed below
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "angular-language-server",
        "ansible-language-server",
        "ansible-lint",
        "azure-pipelines-language-server",
        "css-variables-language-server",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "elixir-ls",
        "gradle-language-server",
        "grammarly-languageserver",
        "graphql-language-service-cli",
        "helm-ls",
        "htmlbeautifier",
        "htmlhint",
        "json-lsp",
        "jsonlint",
        "kotlin-language-server",
        "lua-language-server",
        "luacheck",
        "markdownlint",
        "php-cs-fixer",
        "php-debug-adapter",
        "phpcs",
        "phpmd",
        "phpstan",
        "powershell-editor-services",
        "prettier",
        "pretty-php",
        "pylint",
        "pyright",
        "python-lsp-server",
        "shellcheck",
        "shfmt",
        "sql-formatter",
        "sqlfmt",
        "sqls",
        "stylelint",
        "stylua",
        "usort",
        "vtsls",
        "yaml-language-server",
        "yamlfix",
        "yamllint",
      },
    },
  },
}
